apisix:
  url: http://127.0.0.1:9080
k8s:
  url: http://192.168.0.80:31177
  namespace: csmp
  workspace: dked
  username: csmp
  password: Dked@213
harbor:
  address: core.harbor.dked:30002
  admin: admin
  password: Harbor12345
  project: csmp
kmc:
  url: http://kmc.csmp:9527
  appid: "csmp"
  appsecret: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpX"
admin:
  url: http://admin.csmp:8100
health:
  url: http://health.csmp:8003
mysql:
  ip: mysql.csmp
  port: 3306
  username: root
  password: 123456
  dbname: demo
  readtimeout: 10000
  writetimeout: 10000
images:
  - model: dk1
    url: 192.168.0.80:30002/csmp/hsmsoft:v3.1.0
    port: 9255

